# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal

services:
  - docker

env:
  global:
    - secure: "P7WHwnWX29zWPsDF1hs/6WAP19tCkqbaaU/b1uOzfkRXZYXNrsSu6btPN452lkUttZreSOVqUdSDLGfHfmUCnYkKsKacn9RFAXkDW8GBvzXD4IhpE4/obz7eY1/6JLc4jjELLT3yeZ1D54QbY7Zucs0zDOsg/V8eCCTPYMpoxEj/s+rgZF1ZRFuwK/T82iJEcaplQ0nG7YkNJ1jsQ67r95oPgmAdzSdjPybMe46Uz3Hz+u4qRNjLOIa21Ttgh7GwXrNIDmbeb8f/hvVfoPSq+InuK3eVIsmQwduFmk/DvST3DGBbTrtLMOek82orDpo3xikPhQumD9Yya/Y7vnH5R8COHOD6+WEcXB/4z/HFE5xSzaEIX0UGQobpTfAy3TjTIAzuWbuIgbLY5cc/7bkaW+6ltEKYzBL8ltSkCrDPVuR0fp86dEX0d+C2bOC4eqv+4kGIkw0YJcJGEV69vUUUINGsydKV3lxN0loCbOkt8hRhqyD1Cms9LUrECd8WaWmIlKComIWbBokHfX+RQbzxrECzUx49c9TXHlO3nL8h7ngQjmIYprXgV5ft5eslQvNomZWuQeyqJG6b8j3Jb0ivR0yuYgd7ZRpAMkz69RjP5qY5PT6Z5FeNWsRv0Au7Gn0qEpzEVwDp9qDN/ahp0xltpVk6Dz6wBdJ5nwU3deCOZhQ="
    - secure: "atQeCSwtUIF2ybtM3aN2IT1P9YLW2s0ihfQmGPbZ0HeQqYowFY1evQler0uYWLh9AwsLcjZRTcvme7a3sr1WOE64+BjkvnYlnACfQj7y8IJeDjUuHcQbIeFbaZVM6EudWw4ddqmKlxgBy8Uqpwsh6n1B3dNESSrlLuUMSGwjeQXERnLX2HmdHarpc5dbwiP2BhnhHb4pz+mi/Xk8Oc7DJqMuyK54Pl5FI/ycYNexA3aWR/F/O1DFA79iR8yCNkBYXQZ23qKAHdgNrSjJH70IQelfAKqK38ruSr4YdbbhV3fobn3ZXpP4WTDNOg4pj59KEhSfsRDaTuPA4k9fdphhoUrlm4g04jhVVXouBE6unMEpBswyufXDh6xhj48yw7IxCHe9vCHvi6ww+hK5mPFLz5WdSDX1ZZF3+u5mOk4ZHaB4pvx1KKl1qVj6tvJoksrPcyWE/DG/66NGV4rwWlP0c0D2tZj1a6L3ulhl8jJpdXCi3fDO4/nA3D6zkwIiCM0ptSoiyC4qClBGUhikbRpqDJol+xNd6PB+JWFky6W0RFOOu9en7wSOc9cXDfNkKcFQw0vyzS06WIN+tecxMOyYnPfugGxJUcyvjBvPpZN+H6wKwfMDFjzdCRE3jwsZFYrduT60ooEczFshXsTgall1jlyUbiB8F1eXQVPZ0f+nCyg="

before_install:
  - docker info

script:
  - bash docker_build_and_push
