#!/bin/bash
docker build \
    --build-arg SDK_ARCHIVE_VERSION \
    -t android-tools \
    android-tools/
docker tag android-tools $DOCKER_USERNAME/android-tools
docker images
docker push $DOCKER_USERNAME/android-tools
