#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t android-tools android-tools/
docker images
docker tag android-tools $DOCKER_USERNAME/android-tools
docker push $DOCKER_USERNAME/android-tools
